name: "Create Sync PR"
author: Rahul Singh Mawari <rsmawari198@gmail.com>
description: "Github Action to create PR for syncing multiple branches"
branding:
  icon: git-pull-request
  color: green
inputs:
  GITHUB_TOKEN:
    description: "User token to be associated with this pull request."
    required: true
  SOURCE_BRANCH:
    description: "Branch from make pull-request from"
    required: true
  TARGET_BRANCH:
    description: "Branch to make the pull-request against"
    required: true
  REVIEWERS:
    description: "Users to review the pull-request"
    required: false
  TEAM_REVIEWERS:
    description: "Team slug to review the pull request"
    required: false
outputs:
  PULL_REQUEST_URL:
    description: "URL for either the generated pull request or the currently open one"
  PULL_REQUEST_NUMBER:
    description: "Pull request number from generated pull request or the currently open one"
runs:
  using: "node16"
  main: "dist/index.js"
